### ISSUE TITLE
Scaffold Project

### ISSUE THREAD

**Issue by sethmbrown** [scidsg/semiphemeral-ui#1]
### Tasks

- [ ] Enable TS strict mode
- [ ] Enable `swcMinify` and `productionBrowserSourceMaps` in `next.config.js`
- [ ] Install and configure TanStack Query provider
- [ ] Install Zustand
